name: amfistk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^29.2.5
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/images/stk.jpg
    - assets/images/tritriva.jpg
    - assets/images/nature.jpg
    - assets/images/ensemble.jpeg
    - assets/images/mena.jpg
    - assets/images/mi.png
    - assets/pdf/fihavanana.pdf
    - assets/pdf/doc2.pdf
    - assets/pdf/doc3.pdf
    - assets/pdf/azoantoka.pdf
    - assets/pdf/manaiky.pdf
    - assets/pdf/aminaotanora.pdf
    - assets/pdf/fiainambaovao.pdf
    - assets/pdf/fianarana.pdf
    - assets/pdf/mitafia.pdf
    - assets/pdf/tanoratanindrazanao.pdf
    - assets/pdf/tenaaina.pdf
